---
- name: Uninstall amazon-ecr-credential-helper from package
  package:
    name: "{{ aws_ecr_cred_helper_pkg }}"
    state: absent

- name: Set target architecture to amd64
  set_fact:
    target_arch: "amd64"
  when: ansible_architecture == "x86_64"

- name: Set target architecture to arm64
  set_fact:
    target_arch: "arm64"
  when: ansible_architecture == "aarch64"

# https://github.com/awslabs/amazon-ecr-credential-helper/releases
- name: Install amazon-ecr-credential-helper from binary
  get_url:
    url: https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/{{
      aws_ecr_cred_helper_bin_version }}/linux-{{ target_arch }}/docker-credential-ecr-login
    dest: /usr/local/bin/docker-credential-ecr-login
    mode: '0755'
